### ISSUE TITLE
A lot of mongo connections being opened

### ISSUE THREAD

**Issue by michaeltcoelho** [drgarcia1986/muffin-motor#5]
Hi @drgarcia1986 , 

i was playing with `muffin` and your plugin `muffin-motor` on docker containers and i realized that it is opening a lot of connections with mongo as you can see [here](https://goo.gl/syPU6Z). I've still realized that in you code hasn't any `finish` method declared to close opened connections as you can see on [here](https://github.com/klen/muffin-mongo/blob/master/muffin_mongo.py#L62).

Any suggestion?

**Comment by drgarcia1986** [comment]
I removed [here](https://github.com/drgarcia1986/muffin-motor/commit/4a5d732458f70e46f7ba7124732eb053e1e5ac18) because the new version of motor breaks compatibility, but now, I open #6 with the FIX, can you validate?
